// LOADING
export const DISPLAY_LOADING = "DISPLAY_LOADING";

export const HIDE_LOADING = "HIDE_LOADING";


// USER
export const LOGIN = "LOGIN";

export const SIGNUP = "SIGNUP";

export const LOGOUT = "LOGOUT";

export const GET_INVISIBLE_USERS = "GET_INVISIBLE_USERS";

export const GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL";

export const GET_TOP_USERS = "GET_TOP_USERS";

export const GET_LIST_BY_USER = "GET_LIST_BY_USER";

export const CREATE_LIST = "CREATE_LIST";

export const ADD_POST_TO_LIST = "ADD_POST_TO_LIST";

export const DELETE_POST_FROM_LIST = "DELETE_POST_FROM_LIST";

export const GET_TOPIC_BY_USER = "GET_TOPIC_BY_USER";

export const FOLLOW_TOPIC = "FOLLOW_TOPIC";

export const UNFOLLOW_TOPIC = "UNFOLLOW_TOPIC";

export const GET_AUTHOR_POST = "GET_AUTHOR_POST";

export const GET_AUTHOR_SUBSCRIBER = "GET_AUTHOR_SUBSCRIBER";

export const GET_AUTHOR_LIST = "GET_AUTHOR_LIST";

export const IS_FOLLOW_AUTHOR = "IS_FOLLOW_AUTHOR";

export const BLOCK_AUTHOR = "BLOCK_AUTHOR";

export const GET_USER_FOLLOWER = "GET_USER_FOLLOWER";

export const GET_USER_FOLLOW = "GET_USER_FOLLOW";

export const GET_USER_BLOCK = "GET_USER_BLOCK";

export const UNBLOCK_USER = "UNBLOCK_USER";

export const PIN_POST = "PIN_POST";

export const UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const UNPIN_POST = "UNPIN_POST";

export const GET_USER_CURRENT_SUBSCRIPTION = "GET_USER_CURRENT_SUBSCRIPTION";

export const CANCEL_PLAN = "CANCEL_PLAN";


// TOPIC
export const GET_ALL_TOPICS = "GET_ALL_TOPICS";

export const GET_TOPIC_BY_ID = "GET_TOPIC_BY_ID";

// POST
export const GET_ALL_POSTS = "GET_ALL_POSTS";

export const GET_TOP_POSTS = "GET_TOP_POSTS";

export const GET_POST_BY_ID = "GET_POST_BY_ID";

export const GET_POST_BY_USER = "GET_POST_BY_USER";

export const CREATE_POST = "CREATE_POST";

export const UPDATE_POST = "UPDATE_POST";

